Update main.yml to deploy to prod

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -57,3 +57,33 @@ jobs:
 
             # Run the Docker container
             docker run -d -p 80:5000 --name my-python-app-container ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest
+
+      - name: Deploy to PROD EC2
+        uses: appleboy/ssh-action@master
+        with:
+          host: 13.127.130.113
+          username: ubuntu  # Change if needed
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            # Check if Docker is installed
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+            # Install Docker directly using apt
+              sudo apt-get update
+              sudo apt-get install -y docker.io
+            else
+              echo "Docker is already installed."
+            fi
+
+            # Pull the latest Docker image on QA server
+            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest
+
+            # Check if the container exists and remove it if it does
+            if [ $(docker ps -a -q -f name=my-python-app-container-prod) ]; then
+              docker stop my-python-app-container-prod
+              docker rm my-python-app-container-prod
+            fi
+
+            # Run the Docker container on QA server
+            docker run -d -p 80:5000 --name my-python-app-container-prod ${{ secrets.DOCKER_HUB_USERNAME }}/my-python-app:latest
